services:
  app:
    build: ./app
    environment:
      PORT: 33455
      FLAG: ctf4b{dummy_flag}
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 33455:80
    depends_on:
      - app
    restart: always