services:
  app:
    build: ./app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MYSQL_HOST=mysql
      - MYSQL_USER=ctf4b
      - MYSQL_PASSWORD=dummy_pass
      - MYSQL_DATABASE=memodb
      - SESSION_SECRET=dummy_session_secret
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 33456:80
    depends_on:
      - app
    restart: always

  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: dummy_root_pass
      MYSQL_DATABASE: memodb
      MYSQL_USER: ctf4b
      MYSQL_PASSWORD: dummy_pass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  redis:
    image: redis:8-alpine
    volumes:
      - redis:/data
    restart: always

volumes:
  redis: